### ISSUE TITLE
Cluster field is blank for some VMs

### ISSUE THREAD

**Issue by ibishop100** [Oxalide/vsphere-influxdb-go#3]
Hi, I'm so glad I found this tool!  The problem I have run into is some of my VMs show up with the cluster field empty.  I have been looking and haven't found any commonality yet.

Any ideas?

**Comment by sofixa** [comment]
Hi,

Hm, weird. Do you think said VMs coud have been vMotioning at the moment? Are they always the same or does it change? Could you activate debug mode  (launch with -debug ) and paste the output on a gist or something?

Thanks,

Cheers,
Adrian

**Comment by ibishop100** [comment]
I've tried moving the VMs around and compared one which had a clustername to one without and couldn't find any difference.  I'll run in debug mode and get you some logs.  I was thinking I should dump the whole VM data structure out to see what vsphere is reporting differently for a good and a bad one, but go is new to me so that'll take a bit.

**Comment by ibishop100** [comment]
Here is the log...

https://gist.github.com/ibishop100/b19d75fae9d703d00d9974376f0bae73

Thanks, Ian

**Comment by sofixa** [comment]
Hi,

Hm, interesting. Could you check if you have data for each and every one of your hosts? If no, you'll need to restart the host management services.

Cheers,
Adrian

**Comment by exbane** [comment]
I had the same problem with this.. It was because the client was not catching that the VM's are properly being monitored by HA. I know it sounds weird but this is what fixed it for me.. Go to your cluster and edit settings in vCenter - Go to vSphere HA then VM Monitoring. Change it from disabled to enabled. Press OK. Go back in and disable it again. This will cause HA to re-identify all the VMs in the cluster and tag them properly for HA monitoring. This wont cause downtime FYI. Try that and see if it helps.

**Comment by sofixa** [comment]
Thanks for that, @exbane . 

I'll make a FAQ / common issues page and quote you there, if you don't mind :)

Cheers,
Adrian
