### ISSUE TITLE
No graphs with dashboards

### ISSUE THREAD

**Issue by civodul999** [Oxalide/vsphere-influxdb-go#58]
Hello,
I have installed CentOS 7 with grafana Version 4.6.3 and Influx version 1.4.2.
My vmware cluster is running on 6.5 version.
I have downloaded your script and I think it's working fine because I see a lot of datas in the base.
When I import the dashboard you give in the description, the dashboard are null except "cpu ready %" and "cpu usage %" for [this one](https://grafana.com/dashboards/3571)
The metrics level is 4 for each duration.

Is that normal if I see nothing ?
Do I have to create my own dashboard with my own request ?
Or maybe it's not working propely with 6.5 version or the others versions.

Thanks for you reply

**Comment by sofixa** [comment]
Hi, @civodul999 . I've tested the dashboards on vCenter/ESXi 5.0-6.5, and haven't had any issues as long as the metric collection level is at 4 for the first interval. You said that you see metrics in the database, and a few of the graphs work, so i suppose something isn't working as it should on the templating variables level. Could you check what they look like? (At the top of the dashboard there are a few dropdowns allowing choice of vCenter/ESXi, cluster, datastore, etc.) Are all of them with valid values? Could you try changing them a bit(if you have a choice, like select only datastore X or Y) and refreshing to see if that changes anything? Furthermore, do you happen to have a big number of any of them? (I'm asking this because by default Grafana will expand the "All" template variable value to each and every value with a comma; so if you have 5000 datastores, it would result in a 414 URI too long error from InfluxDB; if that's the case, you need to override the default "All" value from the templating settings on the dashboard with /*/, which is just a glob and does basically the same job).

Cheers,
Adrian

**Comment by kolesnikovIV** [comment]
@sofixa , any guide how to enable level 4 for metrics collection for esxi host, no vcenter, cause python script havn't affected, still have "no datasets" in grafana dashboards, can help with it ?

**Comment by sofixa** [comment]
@kolesnikovIV , sorry, that isn't possible, with standalone ESXi hosts you only get a subset of all metrics(basically nothing about provisioning), so the VMware Cloud Overview dashboard should be a little empty, but the other one, VMware performance, should work just fine.
