### ISSUE TITLE
json: cannot unmarshal object into Go struct field Configuration.

### ISSUE THREAD

**Issue by goku-son** [Oxalide/vsphere-influxdb-go#64]
Hi, 

I am trying to set this up on a Redhat system to monitor a standalone ESXi server. This is for a home environment and I don't have any vCenter servers. 

The /etc/vsphere-influxdb-go.json file is configured as follows for the vCenter stanza:

{
  "Domain": ".home",
  "Interval": 60,
  "VCenters": [
    { "Username": "root", "Password": "passw0rd", "Hostname": "10.0.30.153" },
  ],

Not 100% sure if that how that stanza should look with just and ESXi standalone. When I attempt to start
/usr/local/bin/vsphere-influxdb-go in the foreground, I get the following errors: 

Starting vsphere-influxdb-go with config file /etc/vsphere-influxdb-go.json
Could not decode configuration file /etc/vsphere-influxdb-go.json
json: cannot unmarshal object into Go struct field Configuration.VCenters of type []*main.VCenter

Does this work with a standalone ESXi and if it does, can you give me a sense of how the config file should look?

Thanks in advance.

**Comment by sofixa** [comment]
Hi,

Yes, it works with standalone hosts as long as you have a valid(non-free) licence(the API is only available if you're with a paid licence). I think the error is coming from the comma at the end of your line, since you only have one "vcenter" in the "VCenters" JSON array, it should be without a comma at the end, like this:

```
"VCenters": [
{ "Username": "root", "Password": "passw0rd", "Hostname": "10.0.30.153" }
],
```

Cheers,
Adrian
